In [2]:
import pickle
ofname = open("dataset_small.pkl","rb") # x stores input data and y target values
(x,y) = pickle.load(ofname,encoding="latin1")

In [3]:
x

array([[ 3.6000e+03,  2.3750e+03,  7.6310e+01, ..., -1.0000e+00,
        -1.0000e+00,  1.0000e+00],
       [ 2.3000e+04,  2.3000e+04,  7.6789e+02, ..., -1.0000e+00,
        -1.0000e+00,  1.0000e+00],
       [ 7.0000e+03,  7.0000e+03,  2.2584e+02, ..., -1.0000e+00,
        -1.0000e+00,  1.0000e+00],
       ...,
       [ 1.0000e+04,  1.0000e+04,  3.1111e+02, ..., -1.0000e+00,
        -1.0000e+00,  1.0000e+00],
       [ 3.5000e+03,  3.5000e+03,  1.1961e+02, ..., -1.0000e+00,
        -1.0000e+00,  1.0000e+00],
       [ 8.3250e+03,  8.3250e+03,  2.8248e+02, ..., -1.0000e+00,
        -1.0000e+00,  1.0000e+00]])

In [4]:
y

array([ 1.,  1.,  1., ..., -1., -1., -1.])

In [45]:
import numpy as np
X = np.loadtxt("data.csv",delimiter=",")
print("feature matrix has shape",X.shape)
y = np.loadtxt("labels.csv",delimiter=",")
print("label vector has shape",y.shape)


feature matrix has shape (4140, 15)
label vector has shape (4140,)


In [46]:
X[0,:5]

array([3.600e+03, 2.375e+03, 7.631e+01, 3.000e+04, 1.504e+01])

In [47]:
y[-6:]

array([-1., -1., -1., -1., -1., -1.])

In [48]:
from sklearn import neighbors as nbr 
knn = nbr.KNeighborsClassifier(n_neighbors=11)   # specification
knn.fit(x, y)   # training
yhat = knn.predict(x)   # prediction
yhat[-6:]

array([-1., -1., -1., -1., -1., -1.])

In [49]:
n = len(y)
acc = sum(yhat==y)/n
print(f"accuracy is {acc:.1%}")

accuracy is 83.2%


In [50]:
rejected = sum(y==-1)
print(f"{rejected/n:.1%} were rejected")


81.6% were rejected


In [62]:
from sklearn import metrics
C = metrics.confusion_matrix(y,yhat)
print(C)

[[3370    7]
 [ 690   73]]


In [56]:
TP,FP,FN,TN = C.ravel()
print(f"recall = {TP/(TP+FN):.1%}")
print(f"specificity = {TN/(TN+FP):.1%}")
print(f"precision = {TP/(TP+FP):.1%}")
print(f"NPV = {TN/(TN+FN):.1%}")


recall = 99.8%
specificity = 9.6%
precision = 83.0%
NPV = 91.2%


In [65]:
print(metrics.classification_report(y,yhat))

              precision    recall  f1-score   support

        -1.0       0.83      1.00      0.91      3377
         1.0       0.91      0.10      0.17       763

    accuracy                           0.83      4140
   macro avg       0.87      0.55      0.54      4140
weighted avg       0.85      0.83      0.77      4140



In [ ]:
metrics.confusion_matrix()